package net.sourceforge.hourglass.framework;

/**
  * String resource names.
  *
  * Auto-generated by net.sourceforge.hourglass.build.GenerateStringsTask
  * Source File: /home/user/Projects/hourglass/resources/net/sourceforge/hourglass/framework/HourglassPreferences.properties
  * Date: Sun Jan 23 18:15:32 CST 2022
  */
public class Prefs {
  public static final String SAVE_ALL_CHANGES = "SAVE_ALL_CHANGES";
  public static final String AUTOSAVING_ENABLE = "AUTOSAVING_ENABLE";
  public static final String AUTOSAVING_INTERVAL_MINUTES = "AUTOSAVING_INTERVAL_MINUTES";
  public static final String BACKUPS_NUMBER = "BACKUPS_NUMBER";
  public static final String TIMEZONE_USE_DEFAULT = "TIMEZONE_USE_DEFAULT";
  public static final String TIMEZONE = "TIMEZONE";
  public static final String TIME_FORMAT_TYPE = "TIME_FORMAT_TYPE";
  public static final String MAX_INDIRECTIONS = "MAX_INDIRECTIONS";
  public static final String HOURGLASS_DIR_BASENAME = "HOURGLASS_DIR_BASENAME";
  public static final String HOURGLASS_DIR = "HOURGLASS_DIR";
  public static final String ARCHIVE_NAME = "ARCHIVE_NAME";
  public static final String TRANSLATION_RESOURCE_BUNDLE = "TRANSLATION_RESOURCE_BUNDLE";
  public static final String ERROR_DIALOG_COLUMN_WIDTH = "ERROR_DIALOG_COLUMN_WIDTH";
  public static final String TOOLTIP_CHOP_WIDTH = "TOOLTIP_CHOP_WIDTH";
  public static final String TOOLTIP_CHOP_STRING = "TOOLTIP_CHOP_STRING";
}
